assignment-1 submission bhatipradeep
cutting-edge-visionaries/Blockchain pull request #2
Opened 2019-12-13 10:20 UTC by bhatipradeep

2019-12-14 14:41 UTC, johnsoncarl commented on Submissions/bhatipradeep/Assignment-1/solution.py
> +	    node = block(time.ctime(),data,self.chain[len(self.chain)-1].hash)
this is correct!!!

2019-12-14 14:42 UTC, johnsoncarl requested changes

2019-12-14 14:42 UTC, johnsoncarl commented on Submissions/bhatipradeep/Assignment-1/solution.py
> +	    return sha256(self.data.encode()).hexdigest()
You missed adding timestamp and Previoushash

2019-12-14 15:11 UTC, bhatipradeep commented
I already made the changes and made second pull request.

On Sat, 14 Dec, 2019, 8:12 PM AMAN PANDEY, <notifications@github.com> wrote:

> *@johnsoncarl* requested changes on this pull request.
> ------------------------------
>
> In Submissions/bhatipradeep/Assignment-1/solution.py
> <https://github.com/cutting-edge-visionaries/Blockchain/pull/2#discussion_r357921260>
> :
>
> > @@ -0,0 +1,50 @@
> +from hashlib import sha256
> +import time
> +
> +class block():
> +	def __init__(self, timestamp, data, previousHash = ''):
> +		self.timestamp = timestamp
> +		self.data = data
> +		self.previousHash = previousHash
> +		self.hash = self.calculateHash()
> +
> +	def calculateHash(self):
> +	    return sha256(self.data.encode()).hexdigest()
>
> You missed adding timestamp and Previoushash
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cutting-edge-visionaries/Blockchain/pull/2?email_source=notifications&email_token=AKLAWTZD2NZSEEDOUN2FENTQYTWFDA5CNFSM4J2K4GP2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCPGTUXA#pullrequestreview-332216924>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKLAWT6CQSWHTU4443UGPW3QYTWFDANCNFSM4J2K4GPQ>
> .
>

2019-12-16 16:34 UTC, johnsoncarl approved these changes
done 👍

2019-12-16 16:34 UTC, merged