blockchain using python
cutting-edge-visionaries/Blockchain pull request #6
Opened 2019-12-14 14:56 UTC by sonika-shah

2019-12-15 19:37 UTC, johnsoncarl commented on Submissions/sonika-shah/Assignment1/1.py
> +		return sha256((str(self.timestamp) + str(self.data) + str(self.previousHash).encode()).hexdigest())
please check the pranatheses here.

2019-12-15 19:37 UTC, johnsoncarl requested changes
Please remove the inconsistencies

2019-12-16 00:53 UTC, sonika-shah commented
removed the inconsistencies

2019-12-16 16:33 UTC, johnsoncarl approved these changes
cool... Good Work 👍

2019-12-16 16:33 UTC, merged