[Assignment1 code MineBot]
cutting-edge-visionaries/Blockchain pull request #7
Opened 2019-12-14 15:17 UTC by Gaurav-ECE-SVNIT

2019-12-15 19:33 UTC, johnsoncarl commented on Submissions/Gaurav-ECE-SVNIT/Assignment1.py
> +        return sha256((str(self.timestamp)+str(self.data)+str(self.previousHash)).encode()).hexdigest()
will work..!!

Just to make sure I checked it in Python editor, I found inconsistent use of tabs. please correct it in this line

2019-12-15 19:34 UTC, johnsoncarl requested changes
Please make the suggested changes and submit.

2019-12-16 09:45 UTC, Gaurav-ECE-SVNIT commented
I have done the changes please merge it now.

2019-12-16 09:46 UTC, Gaurav-ECE-SVNIT commented
I have made the changes.

2019-12-16 16:30 UTC, johnsoncarl approved these changes
It works,,, good work 👍

2019-12-16 16:31 UTC, merged